distribute-on:
  small-changeset: 3 linux-medium-js # Distribute on small if 1-25% of projects affected in PR
  medium-changeset: 5 linux-medium-js # Distribute on medium if 26-50% of projects affected in PR
